name: Serenity BDD Tests

on:
  push:
    branches:
      - main
      - feature/jenkins-pipeline
  workflow_dispatch:

jobs:
  serenity-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Instalar Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Verificar versión de Chrome
        run: google-chrome --version

      - name: Ejecutar pruebas Serenity
        run: mvn clean verify -Dcucumber.filter.tags="@addProductCart" -Denvironment=certification -Dwebdriver.driver=chrome -Dwebdriver.autodownload=true -Dchrome.switches="--headless=new,--no-sandbox,--disable-dev-shm-usage,--window-size=1920,1080"

      - name: Publicar reporte Serenity
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity